https://stackoverflow.com/a/31324264/

In [1]:
import numpy

def fextract( f ):
  bits = numpy.asarray( f, dtype=numpy.float64 ).view( numpy.int64 )
  if not bits & 0x7fffffffffffffff: # f == +/-0
    return 0, 0
  sign = numpy.sign(bits)
  exponent = ( (bits>>52) & 0x7ff ) - 1075
  mantissa = 0x10000000000000 | ( bits & 0xfffffffffffff )
  # from here on f == sign * mantissa * 2**exponent
  for shift in 32, 16, 8, 4, 2, 1:
    if not mantissa & ((1<<shift)-1):
      mantissa >>= shift
      exponent += shift
  return sign * mantissa, exponent

fextract( 1.5 ) # --> 3, -1

(3, -1)

In [38]:
import numpy as np

In [2]:
a = 42

In [41]:
b = a.to_bytes(3, 'little', signed=True)
b

b'*\x00\x00'

In [42]:
b.hex()

'2a0000'

In [58]:
np.frombuffer(b, dtype='uint8')

array([42,  0,  0], dtype=uint8)

In [59]:
np.unpackbits(np.frombuffer(b, dtype='uint8'))

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=uint8)

In [66]:
np.fromiter(b, dtype='uint8')

array([42,  0,  0], dtype=uint8)

In [88]:
f'{42:024b}'

'000000000000000000101010'

In [74]:
int('01001', 2)

9

two's complement?

In [79]:
bin(-42 - (1 << 24))

'-0b1000000000000000000101010'

In [81]:
int.from_bytes(b'*\x00\x00', byteorder='little')

42

In [75]:
x = 0b11001100
complement = abs(~x) + 0b1
bin(complement)

'0b11001110'

In [76]:
x = 0b11001100
complement = ~abs(x) + 0b1
bin(complement)

'-0b11001100'

In [11]:
a.to_bytes(3, 'big', signed=True)

b'\x00\x00*'

In [16]:
(-42).to_bytes(3, 'big', signed=True)

b'\xff\xff\xd6'

In [17]:
(-42).to_bytes(3, 'little', signed=True)

b'\xd6\xff\xff'

In [21]:
(-1).to_bytes(3, 'big', signed=True)

b'\xff\xff\xff'

In [22]:
import sys

In [25]:
sys.byteorder

'little'

TODO:

* raw WAV vs raw AIFF
* in-memory files